### ISSUE TITLE
AttributeError: 'module' object has no attribute 'command'

### ISSUE THREAD

**Issue by wsy** [twocucao/danmu.fm#17]
$ **_danmu.fm -q 3 -m 1 -p . -vvvv  http://www.douyu.com/444360_**
Traceback (most recent call last):
  File "/usr/local/bin/danmu.fm", line 7, in <module>
    from danmufm.danmu import main
  File "/usr/local/lib/python3.4/dist-packages/danmufm/danmu.py", line 76, in <module>
    @click.command()
AttributeError: 'module' object has no attribute 'command'

**Comment by wsy** [comment]
Environment Ubuntu

**Comment by wsy** [comment]
已经执行过sudo apt install --reinstall python3-click-package命令了。

难道还要单独apt-get install click？

**Comment by hylarucoder** [comment]
你好,执行下面的命令即可

```shell
pip install click 
```

**Comment by hylarucoder** [comment]
可能是Ubuntu安装的Click和这里通过 PIP 版本安装的click不一致.

**Comment by wsy** [comment]
![image](https://user-images.githubusercontent.com/2684991/28303080-bde996f4-6bc3-11e7-9c55-b22b5158519c.png)

**Comment by wsy** [comment]
仍然不行

**Comment by hylarucoder** [comment]
请尝试先卸载掉你的那个ubuntu package 安装的click包
