### ISSUE TITLE
增加把弹幕信息写入到文件的命令行选项

### ISSUE THREAD

**Issue by zhaozhao** [twocucao/danmu.fm#3]

**Comment by hylarucoder** [comment]
写入文件? 在命令行后面加个 > 不就好了么?

**Comment by zhaozhao** [comment]
我一开始以为是那logging模块输出弹幕信息的，看了一下源码原来是print输出的，>的重定向到文件会有flush的问题。

**Comment by hylarucoder** [comment]
@zhaozhao 哈哈,其实用多线程放到队列,写文件还是有这个问题的.

**Comment by zhaozhao** [comment]
@twocucao 你0.3版本里面引入sqlalchemy用postgresql感觉有点重了 我觉得sqlite已经能够满足需求。

**Comment by hylarucoder** [comment]
sqlite作为分析工具的话,貌似有点功能上不够强大吧,那我在开发的时候加个默认选项好了,默认sqlite进行存储,如果指定的postgresql的话,就使用postgresql好了.
