### ISSUE TITLE
我按你文档写的命令运行出错了

### ISSUE THREAD

**Issue by ecliar** [twocucao/danmu.fm#4]
![image](https://cloud.githubusercontent.com/assets/1331705/16518198/29608060-3fb4-11e6-8703-b043fde98945.png)
它说没有-m -p的命令
![image](https://cloud.githubusercontent.com/assets/1331705/16518238/4f605966-3fb4-11e6-9539-5057adeaf9b8.png)
然后我去掉这两命令后他又说没有mplayer，试了好多命令都不行。。。
![image](https://cloud.githubusercontent.com/assets/1331705/16518372/ff3a184a-3fb4-11e6-869f-57b29c326fef.png)
这个命令也不行，应该是代码有问题

**Comment by hylarucoder** [comment]
Sorry, 那个是第二版本,我的源码更新到0.3版本了,但是pip仓库里面还是0.2版本.pip 仓库已经升级.

Just Run 

``` bash
pip install danmu.fm --no-cache-dir --upgrade
```
