### ISSUE TITLE
douyu_client.py中101行构造出的用来请求用户验证信息的url貌似已经失效了

### ISSUE THREAD

**Issue by ysrotciv** [twocucao/danmu.fm#6]
启动时会抛如下的异常
  File "/usr/local/lib/python3.5/site-packages/danmufm/client/douyu_client.py", line 106, in fetch_rtmp_info
    if str(js_data["data"]["rtmp_live"]).strip() == "":
TypeError: string indices must be integers

我用项目中构造的如下 url
http://douyutv.com/api/v1/room/499656?aid=android&client_sys=android&time=1469440818&auth=df0506b570038c2eea6d273c95f25b70
请求的结果为:
{'data': 'api身份信息错误', 'error': 1002}

**Comment by hylarucoder** [comment]
正在调试中,可能Douyu的rtmp获取认证方式已经发生变化.

**Comment by hylarucoder** [comment]
暂时去掉了获取RTMP视频流的部分,等获知新的方法之后再添加.
